name: Ubuntu 24.04 CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.16.x'
      - name: Configure
        run: cmake -DCMAKE_INSTALL_PREFIX:PATH=destination -B build
      - name: Build
        run: cmake --build build
      - name: Run basic tests
        run: cd build && ctest --output-on-failure 
      - name: install
        run: cmake --install build --verbose
      - name: Run installation tests
        run: cd tests/install &&  cmake -DCMAKE_INSTALL_PREFIX:PATH=../../destination -B build && cmake --build build

